"""Added status column to Order model with default 'Pending'

Revision ID: 120b5faeabea
Revises: 9372b734e5f6
Create Date: 2024-10-08 16:04:00.348270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120b5faeabea'
down_revision = '9372b734e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
